server:
  port: 8080

spring:
  datasource:
    # H2 in-memory database for local development
    url: jdbc:h2:mem:caredb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false
  mail:
    # AWS WorkMail SMTP for local development
    host: smtp.mail.us-east-1.awsapps.com
    port: 465
    username: info@careridesolutionspa.com
    password: Transportation1@@
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          from: info@careridesolutionspa.com
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
        debug: true

# Logging configuration
logging:
  level:
    com.care.ride.service.EmailService: DEBUG
    org.springframework.mail: DEBUG
    javax.mail: DEBUG

jwt:
  secret: local_development_secret_key_change_in_production

# Enable CORS for local development
cors:
  allowed-origins: http://localhost:4200,http://localhost:4201
