# Copy this file to application-secrets.yml (DO NOT COMMIT the real one)
# It will be imported optionally if you uncomment spring.config.import in application.yml
# Production: prefer environment variables instead of committing secrets.

mail:
  notify: contact@careridesolutionspa.com
spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: contact@careridesolutionspa.com
    password: Transportation1@@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
