
server:
  port: 8080
# Optional external secrets file (not committed) can be added as application-secrets.yml
# spring.config.import: optional:classpath:application-secrets.yml
# Deploy with corrected MAIL_USERNAME GitHub secret
spring:
  datasource:
    # Prefer full SPRING_DATASOURCE_URL if provided, otherwise build from DB_* pieces (default service name 'db').
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:caredb}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:careuser}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASS:changeme_db_password}}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
  show_sql: false
  flyway:
    enabled: false
  mail:
    # HARD-CODED Microsoft SMTP (TEMPORARY - user chose option C)
    host: smtp.office365.com
    port: 587
    username: contact@careridesolutionspa.com
    password: Transportation1@@
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          from: contact@careridesolutionspa.com
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        debug: false
# Custom notification recipient (MAIL_NOTIFY) is consumed directly via @Value in PublicController.
mail:
  notify: contact@careridesolutionspa.com
jwt:
  secret: ${JWT_SECRET:CHANGE_ME}

# Actuator management (production)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
      group:
        readiness:
          include: db
        liveness:
          include: ping
  health:
    mail:
      enabled: false
    db:
      enabled: true

