server:
  port: 8080

spring:
  datasource:
    # H2 in-memory database for local development
    url: jdbc:h2:mem:caredb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false
  mail:
    # Microsoft SMTP for local development testing
    host: smtp.office365.com
    port: 587
    username: contact@careridesolutionspa.com
    password: Transportation1@@
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          from: contact@careridesolutionspa.com
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        debug: true

# Logging configuration
logging:
  level:
    com.care.ride.service.EmailService: DEBUG
    org.springframework.mail: DEBUG
    javax.mail: DEBUG

# Email notification recipient  
mail:
  notify: contact@careridesolutionspa.com

jwt:
  secret: local_development_secret_key_change_in_production

# Enable CORS for local development
cors:
  allowed-origins: http://localhost:4200,http://localhost:4201

# Actuator management endpoints (local only)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
